# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               'James Graham'
tagline:             'JavaScript Developer'
description:         "Hello. I make web apps with JavaScript, using frameworks and libraries like Node, Angular, Aurelia and React."
url:                 ''
baseurl:             ''

# About/contact
author:
  name:              James Graham
  url:               https://twitter.com/jgraham101
  email:             mail@jamesgraham.io

# Custom vars
version:             1.0.0
